package actions

import (

  "fmt"
  "net/http"
  "github.com/gobuffalo/buffalo"
  "github.com/gobuffalo/pop/v5"
  "github.com/gobuffalo/x/responder"
  "example_app/models"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (Blog)
// DB Table: Plural (blogs)
// Resource: Plural (Blogs)
// Path: Plural (/blogs)
// View Template Folder: Plural (/templates/blogs/)

// BlogsResource is the resource for the Blog model
type BlogsResource struct{
  buffalo.Resource
}

// List gets all Blogs. This function is mapped to the path
// GET /blogs
func (v BlogsResource) List(c buffalo.Context) error {
  // Get the DB connection from the context
  tx, ok := c.Value("tx").(*pop.Connection)
  if !ok {
    return fmt.Errorf("no transaction found")
  }

  blogs := &models.Blogs{}

  // Paginate results. Params "page" and "per_page" control pagination.
  // Default values are "page=1" and "per_page=20".
  q := tx.PaginateFromParams(c.Params())

  // Retrieve all Blogs from the DB
  if err := q.All(blogs); err != nil {
    return err
  }

  return responder.Wants("html", func (c buffalo.Context) error {
    // Add the paginator to the context so it can be used in the template.
    c.Set("pagination", q.Paginator)

    c.Set("blogs", blogs)
    return c.Render(http.StatusOK, r.HTML("/blogs/index.plush.html"))
  }).Wants("json", func (c buffalo.Context) error {
    return c.Render(200, r.JSON(blogs))
  }).Wants("xml", func (c buffalo.Context) error {
    return c.Render(200, r.XML(blogs))
  }).Respond(c)
}

// Show gets the data for one Blog. This function is mapped to
// the path GET /blogs/{blog_id}
func (v BlogsResource) Show(c buffalo.Context) error {
  // Get the DB connection from the context
  tx, ok := c.Value("tx").(*pop.Connection)
  if !ok {
    return fmt.Errorf("no transaction found")
  }

  // Allocate an empty Blog
  blog := &models.Blog{}

  // To find the Blog the parameter blog_id is used.
  if err := tx.Find(blog, c.Param("blog_id")); err != nil {
    return c.Error(http.StatusNotFound, err)
  }

  return responder.Wants("html", func (c buffalo.Context) error {
    c.Set("blog", blog)

    return c.Render(http.StatusOK, r.HTML("/blogs/show.plush.html"))
  }).Wants("json", func (c buffalo.Context) error {
    return c.Render(200, r.JSON(blog))
  }).Wants("xml", func (c buffalo.Context) error {
    return c.Render(200, r.XML(blog))
  }).Respond(c)
}

// New renders the form for creating a new Blog.
// This function is mapped to the path GET /blogs/new
func (v BlogsResource) New(c buffalo.Context) error {
  c.Set("blog", &models.Blog{})

  return c.Render(http.StatusOK, r.HTML("/blogs/new.plush.html"))
}
// Create adds a Blog to the DB. This function is mapped to the
// path POST /blogs
func (v BlogsResource) Create(c buffalo.Context) error {
  // Allocate an empty Blog
  blog := &models.Blog{}

  // Bind blog to the html form elements
  if err := c.Bind(blog); err != nil {
    return err
  }

  // Get the DB connection from the context
  tx, ok := c.Value("tx").(*pop.Connection)
  if !ok {
    return fmt.Errorf("no transaction found")
  }

  // Validate the data from the html form
  verrs, err := tx.ValidateAndCreate(blog)
  if err != nil {
    return err
  }

  if verrs.HasAny() {
    return responder.Wants("html", func (c buffalo.Context) error {
      // Make the errors available inside the html template
      c.Set("errors", verrs)

      // Render again the new.html template that the user can
      // correct the input.
      c.Set("blog", blog)

      return c.Render(http.StatusUnprocessableEntity, r.HTML("/blogs/new.plush.html"))
    }).Wants("json", func (c buffalo.Context) error {
      return c.Render(http.StatusUnprocessableEntity, r.JSON(verrs))
    }).Wants("xml", func (c buffalo.Context) error {
      return c.Render(http.StatusUnprocessableEntity, r.XML(verrs))
    }).Respond(c)
  }

  return responder.Wants("html", func (c buffalo.Context) error {
    // If there are no errors set a success message
    c.Flash().Add("success", T.Translate(c, "blog.created.success"))

    // and redirect to the show page
    return c.Redirect(http.StatusSeeOther, "/blogs/%v", blog.ID)
  }).Wants("json", func (c buffalo.Context) error {
    return c.Render(http.StatusCreated, r.JSON(blog))
  }).Wants("xml", func (c buffalo.Context) error {
    return c.Render(http.StatusCreated, r.XML(blog))
  }).Respond(c)
}

// Edit renders a edit form for a Blog. This function is
// mapped to the path GET /blogs/{blog_id}/edit
func (v BlogsResource) Edit(c buffalo.Context) error {
  // Get the DB connection from the context
  tx, ok := c.Value("tx").(*pop.Connection)
  if !ok {
    return fmt.Errorf("no transaction found")
  }

  // Allocate an empty Blog
  blog := &models.Blog{}

  if err := tx.Find(blog, c.Param("blog_id")); err != nil {
    return c.Error(http.StatusNotFound, err)
  }

  c.Set("blog", blog)
  return c.Render(http.StatusOK, r.HTML("/blogs/edit.plush.html"))
}
// Update changes a Blog in the DB. This function is mapped to
// the path PUT /blogs/{blog_id}
func (v BlogsResource) Update(c buffalo.Context) error {
  // Get the DB connection from the context
  tx, ok := c.Value("tx").(*pop.Connection)
  if !ok {
    return fmt.Errorf("no transaction found")
  }

  // Allocate an empty Blog
  blog := &models.Blog{}

  if err := tx.Find(blog, c.Param("blog_id")); err != nil {
    return c.Error(http.StatusNotFound, err)
  }

  // Bind Blog to the html form elements
  if err := c.Bind(blog); err != nil {
    return err
  }

  verrs, err := tx.ValidateAndUpdate(blog)
  if err != nil {
    return err
  }

  if verrs.HasAny() {
    return responder.Wants("html", func (c buffalo.Context) error {
      // Make the errors available inside the html template
      c.Set("errors", verrs)

      // Render again the edit.html template that the user can
      // correct the input.
      c.Set("blog", blog)

      return c.Render(http.StatusUnprocessableEntity, r.HTML("/blogs/edit.plush.html"))
    }).Wants("json", func (c buffalo.Context) error {
      return c.Render(http.StatusUnprocessableEntity, r.JSON(verrs))
    }).Wants("xml", func (c buffalo.Context) error {
      return c.Render(http.StatusUnprocessableEntity, r.XML(verrs))
    }).Respond(c)
  }

  return responder.Wants("html", func (c buffalo.Context) error {
    // If there are no errors set a success message
    c.Flash().Add("success", T.Translate(c, "blog.updated.success"))

    // and redirect to the show page
    return c.Redirect(http.StatusSeeOther, "/blogs/%v", blog.ID)
  }).Wants("json", func (c buffalo.Context) error {
    return c.Render(http.StatusOK, r.JSON(blog))
  }).Wants("xml", func (c buffalo.Context) error {
    return c.Render(http.StatusOK, r.XML(blog))
  }).Respond(c)
}

// Destroy deletes a Blog from the DB. This function is mapped
// to the path DELETE /blogs/{blog_id}
func (v BlogsResource) Destroy(c buffalo.Context) error {
  // Get the DB connection from the context
  tx, ok := c.Value("tx").(*pop.Connection)
  if !ok {
    return fmt.Errorf("no transaction found")
  }

  // Allocate an empty Blog
  blog := &models.Blog{}

  // To find the Blog the parameter blog_id is used.
  if err := tx.Find(blog, c.Param("blog_id")); err != nil {
    return c.Error(http.StatusNotFound, err)
  }

  if err := tx.Destroy(blog); err != nil {
    return err
  }

  return responder.Wants("html", func (c buffalo.Context) error {
    // If there are no errors set a flash message
    c.Flash().Add("success", T.Translate(c, "blog.destroyed.success"))

    // Redirect to the index page
    return c.Redirect(http.StatusSeeOther, "/blogs")
  }).Wants("json", func (c buffalo.Context) error {
    return c.Render(http.StatusOK, r.JSON(blog))
  }).Wants("xml", func (c buffalo.Context) error {
    return c.Render(http.StatusOK, r.XML(blog))
  }).Respond(c)
}
